name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ardurflask:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ardurflask:latest

      - name: Install AWS CLI
        run: |
          pip install --upgrade awscli

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name titleindexing \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=ardurtech,S3Key=deploy.zip \
            --region ${{ env.AWS_REGION }}
          aws elasticbeanstalk update-environment \
            --application-name titleindexing \
            --environment-name Titleindexing-env \
            --version-label ${{ github.sha }} \
            --region ${{ env.AWS_REGION }}
